########### ETHERNET B ##########
set_property -dict { PACKAGE_PIN H11  IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd0}]
set_property -dict { PACKAGE_PIN J11  IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd1}]
set_property -dict { PACKAGE_PIN H9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd2}]
set_property -dict { PACKAGE_PIN J10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd3}]
set_property -dict { PACKAGE_PIN H12  IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd4}]
set_property -dict { PACKAGE_PIN F10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd5}]
set_property -dict { PACKAGE_PIN G10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd6}]
set_property -dict { PACKAGE_PIN F9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_txd7}]

set_property -dict { PACKAGE_PIN A13  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd0}]
set_property -dict { PACKAGE_PIN B12  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd1}]
set_property -dict { PACKAGE_PIN B11  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd2}]
set_property -dict { PACKAGE_PIN A10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd3}]
set_property -dict { PACKAGE_PIN B10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd4}]
set_property -dict { PACKAGE_PIN A9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd5}]
set_property -dict { PACKAGE_PIN B9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd6}]
set_property -dict { PACKAGE_PIN A8   IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxd7}]

set_property -dict { PACKAGE_PIN G9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_mdio}]
set_property -dict { PACKAGE_PIN H8   IOSTANDARD LVCMOS25 } [get_ports {eth_b_mdc}]
set_property -dict { PACKAGE_PIN D8   IOSTANDARD LVCMOS25 } [get_ports {eth_b_gtxclk}]
set_property -dict { PACKAGE_PIN J8   IOSTANDARD LVCMOS25 } [get_ports {eth_b_reset}]
set_property -dict { PACKAGE_PIN E10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxclk}]
set_property -dict { PACKAGE_PIN A12  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxdv}]
set_property -dict { PACKAGE_PIN D10  IOSTANDARD LVCMOS25 } [get_ports {eth_b_rxer}]
set_property -dict { PACKAGE_PIN F8   IOSTANDARD LVCMOS25 } [get_ports {eth_b_txen}]
set_property -dict { PACKAGE_PIN D9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_txer}]
set_property -dict { PACKAGE_PIN C9   IOSTANDARD LVCMOS25 } [get_ports {eth_b_txclk}]

