########### ETHERNET A ##########
set_property -dict { PACKAGE_PIN G12  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd0}]
set_property -dict { PACKAGE_PIN E11  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd1}]
set_property -dict { PACKAGE_PIN G11  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd2}]
set_property -dict { PACKAGE_PIN C14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd3}]
set_property -dict { PACKAGE_PIN D14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd4}]
set_property -dict { PACKAGE_PIN C13  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd5}]
set_property -dict { PACKAGE_PIN C11  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd6}]
set_property -dict { PACKAGE_PIN D13  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txd7}]

set_property -dict { PACKAGE_PIN H14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd0}]
set_property -dict { PACKAGE_PIN J14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd1}]
set_property -dict { PACKAGE_PIN J13  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd2}]
set_property -dict { PACKAGE_PIN H13  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd3}]
set_property -dict { PACKAGE_PIN B15  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd4}]
set_property -dict { PACKAGE_PIN A15  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd5}]
set_property -dict { PACKAGE_PIN B14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd6}]
set_property -dict { PACKAGE_PIN A14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxd7}]

set_property -dict { PACKAGE_PIN K15  IOSTANDARD LVCMOS33 } [get_ports {eth_a_mdio}]
set_property -dict { PACKAGE_PIN M16  IOSTANDARD LVCMOS33 } [get_ports {eth_a_mdc}]
set_property -dict { PACKAGE_PIN F13  IOSTANDARD LVCMOS25 } [get_ports {eth_a_gtxclk}]
set_property -dict { PACKAGE_PIN D11  IOSTANDARD LVCMOS25 } [get_ports {eth_a_reset}]
set_property -dict { PACKAGE_PIN C12  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxclk}]
set_property -dict { PACKAGE_PIN G14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxdv}]
set_property -dict { PACKAGE_PIN F14  IOSTANDARD LVCMOS25 } [get_ports {eth_a_rxer}]
set_property -dict { PACKAGE_PIN F12  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txen}]
set_property -dict { PACKAGE_PIN E13  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txer}]
set_property -dict { PACKAGE_PIN E12  IOSTANDARD LVCMOS25 } [get_ports {eth_a_txclk}]

